sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script: local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Ye4OV6Bi/xPWXQMV0PO1kCV9cpQsyMA9AnnAkgzrFgzYfdafRUy/4qP0c7f/9jWC8OeTiDnLn3ntsGtPf+XBXnUUlyfktrwukdw/6d2gjspUL05vHYqMfeq/UCU6dDtTjoopw1Df6+9fe3qdSMOeaxNS6FD1GyHvrtLbTMQBb24LolbuMqNMyBGcGJyUU13Fplc4Fdc7V9BooZjxEzehyo7LZvyG7l7nL8ilG0vFNIlJbzaRqUHw6SvzXjxeJ+0hjXzNbcaYQcESvDGM6RppclkF68YOxFY1wYvhsYIW3cVdBPTYGnkedlhL9QVLirIy25slzW709BEd2T7Bu+utMc3yxwwiX2pr5ij5jSuvKKnn6OwGN1bNIb6mJwPAsyoMdsbbhc+3UpVkb8sE7Ewi77QF2mb61QGusIVhZ+Qr1iSqdc3gxdtvG6QGQL+RF/gR8xAwRi29932NikTSpt8e9IEHe4enlZs9Vcdf4qA/JtOJ56HfCaUardfzm1m6UjLfcV4PgEMz5D5fQ4w1x6MiEv7v/FhF6cwmcNGWB/JmxAStPkj/qCkLlP7hCauS/pzSjuYvwBZ9ijHqU/UcxmXdGF7rkheiZGiKsst8uhmOYHv4Rgr4sNIWhZzBZ7MFIV5GHepF3A8iznoBN/YCwR89Scrlqro5RzTKgb19BFitk+I=
  - secure: ER1owvBOnzSRT2r41J1qjEmnpcsOZe66yOOrEQlZFOpZCl1NWNFn1HqRJtVJbZcLfYMOyuoaOIdJsQOJl3Irj+itdiNCIkfdw+C1piRdu0ISFWRNyRrhyFiTj4VD96gyzsJNCUnlAWE167cI4JBRHLG+YY64DUDstDrVy/6geEsS+cxjl3U84+awSEVysNWJHpi6IB4gW1U5TXL6BwZXSaNujVymUdz2S3ZhF3kp2Y5YF8BNhFraBYqKNHBGNeetb1P/M/D4/Un5yY7BtWPxo3FF7yVIuIJvFkZC5BYdTtprTdHKx8/fo3S6/DKC2U3Y3A/IevZfvsSHlGR9GNwCYA9kkFNjOxsatGtBJaXG/qXTK8OoJIg7SqcdMLW/eeyXnK34kZZiOOI/3aXbprXb7RDyI2xGrUdBCAHhMvr8fLgIP0bwDUJ2oEWbbNk/Y8lNTrBGKP/HlRLoVy4lpMlT5bpVv7UVDjegqsBYSmX1aAP1ZJfG2eNUb2mj+0krpVKWEVOVMdvqeS3VBRDvbgmozo9V3IqcOVjaqKGEWqDcCZul3urJ0DfkN1e/lAVh60jP1k6NU4UarGp1G9p0rJm0c8+jwvQmZbZfpnKh7AoRaQRM9uDC6aN0bCazHGTr/GKenUKSw7xXxwLfTR+Phti5Mv7ksH08PltzdVS6yG727fI=
  - secure: UknQg1xSzIOCjc1A4MgTaTT6J8ILImqXsSrV4RQ+JObyjGV71IcnA7LPaiKUXOE5z6AS6PD492G9Go7lyBg2gFDvO8hDV1wcyColqh+Uon3vFA1QUQnCqIsmOjR+bo2oollRjlOkZ0max4VrcKsRT4zffVY0oKOnnv6oxEHDsN4fznCGJ+Gj0Pna276soD026Poc3zOF67jd3V5bN+2SEWqRf03oAKHiDDKvAhmNLbD2u1gIJIVE6EaoI8Ara79TL23frwmqU/927icIQP3QNdIdXmqsHYSeNGeukwDNFTdcyZBT5KcH8gt7e6aD6ItuqJU3jJ5EtAfjwZpRcjiGH3UzpHzT/qvYGcR91SZX0jn4agxpUbhFqb0t55u50vFOWw8aDLLqwwy7fRtnNYIgE54LIo6SZHm4J1Vpi02V+sErLLVdiavkAXqx7kSQVykLxZnNH9FsykzYNrCMGtIruKonb0/4wMoYbLEyjBI8LSYLhTpszJkIrYEw5k03JefwoTZedsellvLVbCBVrHRh5CoSwdyeiaLNfsWRfNzkZnRZiF965zxbS82u8NZzPb5+KFTRR22pkjpYeFhPL27w5C5vgdCLL2u9TsX3aVKV1GWzKsJpWTun2Kqd3ZmYMO3eysNZB1o2LOxGdGGo6bzowkjjbDCBg0I2UD1x+Z97ZU4=
  - secure: JM5+NUgSnczYq651ygQqMLyk2BbqQr0ROaZi9QywMCIEWvxYg567jcbGCqpSo+6BtMhpRCPs4hIzrvrJ1S17UMcXPsBGtF34fQsb7XZxP59sZcfhaWCN8zXuU9NSFKIhrYX9sR1eJxuhiB27emOO2Tvbbraxyas4yIovWD6612Rnpr41jiIt5rXupYigU1BHFaVYcvnAlN8XOLn3L3xlOysK6RM5zgAfupi7GBS9l0TtW+44PZ2VqVvyENLrlOyJ1myUvmHCjYIouHRF/Es2+U5DafE+FbyinVtJmuzEJHdQ/cLuk7woyXzUTVFvjZ3TZdY+Jca1vQHTLR9igsG3y9U/USHYmK8jvHWHFYEqazJQcHGVmiaJyXuyyaXQ7zZLwJYW+Z00Ep2iL3IefsCwF9WfNzsIfxJBbbosxaENKEIHlkGHqcWXPqI66UzvbPwZ7dUETmJ9plDIIFmHmf22oRzrkbxgaVkCEknHVgQZvJVtCVHJlCnA1ic4WLpp9kISaWbcaVY1nkpCLLfO5DZuNogiYenHFfVtQqV8cFzuk7jIsepPa1P2OYYxdMpYs23CtZAaMOvzGshYIgAxasZM8Rw3lLDJSjxbwv1oserHI2rRb/lxxFV8NsG4fVle5k832j2CVKANa9rrwogf+CHNRfCZOiDlK+JafbWTX+Vbn1U=
