sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
before_script:
  - npm install bower
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
  - bower install
script:
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k
    "$password" -in id_rsa.enc -out deploy_key -d; fi
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
